name: Stale checker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is stale because it has been open 50 days with no activity.'
          days-before-stale: 50
          days-before-close: -1
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }} 
